# Generated by Django 5.1.6 on 2025-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='name',
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.CharField(),
        ),
    ]
